{{- $dirinit_image := .Values.image.dirinit_container_override | default (printf "%s/dirinit:%s" .Values.image.repository .Chart.AppVersion) }}
{{- $opensearch_image := .Values.image.opensearch_container_override | default (printf "%s/opensearch:%s" .Values.image.repository .Chart.AppVersion) }}
{{- if .Values.opensearch.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
spec:
  ports:
    - port: 9200
      protocol: TCP
      name: http
  selector:
    name: opensearch

---
apiVersion: v1
kind: Service
metadata:
  name: opensearch-headless
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: 9200
      protocol: TCP
      name: http
    - port: 9300
      protocol: TCP
      name: transport
  selector:
    name: opensearch

---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-keystore
type: Opaque

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch
spec:
  selector:
    matchLabels:
      name: opensearch
  serviceName: opensearch-headless
{{- if .Values.opensearch.singleNode }}
  replicas: 1
{{- else }}
  replicas: {{ .Values.opensearch.replicas }}
{{- end }}
  volumeClaimTemplates:
{{- if .Values.is_production }}
  {{- with .Values.storage.production }}
    - metadata:
        name: opensearch-claim
      spec:
        storageClassName: {{ .opensearch_claim.className }}
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: {{ .opensearch_claim.size }}
    - metadata:
        name: opensearch-backup-claim
      spec:
        storageClassName: {{ .opensearch_backup_claim.className }}
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: {{ .opensearch_backup_claim.size }}
  {{- end }}
{{- else }}
  {{- with .Values.storage.development }}
    - metadata:
        name: opensearch-claim
      spec:
        storageClassName: {{ .opensearch_claim.className }}
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: {{ .opensearch_claim.size }}
    - metadata:
        name: opensearch-backup-claim
      spec:
        storageClassName: {{ .opensearch_backup_claim.className }}
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: {{ .opensearch_backup_claim.size }}
  {{- end }}
{{- end }}
  template:
    metadata:
      labels:
        name: opensearch
    spec:
      containers:
      - name: opensearch-container
        image: "{{ .Values.image.repository }}/opensearch:{{ .Values.image.opensearch_tag | default .Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        stdin: false
        tty: true
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        ports:
          - name: http
            protocol: TCP
            containerPort: 9200
          - name: transport
            protocol: TCP
            containerPort: 9300
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          - configMapRef:
              name: opensearch-env
        env:
          - name: VIRTUAL_HOST
            value: "os.malcolm.local"
        volumeMounts:
          - mountPath: /var/local/ca-trust/configmap
            name: opensearch-var-local-catrust-volume
          - mountPath: /var/local/curlrc/secretmap
            name: opensearch-opensearch-curlrc-secret-volume
          - mountPath: "/usr/share/opensearch/data"
            name: opensearch-claim
          - mountPath: "/opt/opensearch/backup"
            name: opensearch-backup-claim
          - name: opensearch-keystore-default-secret-volume
            mountPath: /usr/share/opensearch/config/bootstrap/secretmap
          - name: opensearch-claim
            mountPath: /usr/share/opensearch/config/persist
            subPath: "opensearch"
      initContainers:
      - name: opensearch-dirinit-container
        image: "{{ $dirinit_image }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        stdin: false
        tty: true
        securityContext:
          runAsGroup: 0
          runAsUser: 0
        envFrom:
          - configMapRef:
              name: process-env
        env:
          - name: PUSER_MKDIR
            value: "/data/config:opensearch;/data/opensearch:nodes"
        volumeMounts:
          - name: opensearch-claim
            mountPath: "/data/opensearch"
          - name: opensearch-claim
            mountPath: "/data/config"
      volumes:
        - name: opensearch-var-local-catrust-volume
          configMap:
            name: var-local-catrust
        - name: opensearch-opensearch-curlrc-secret-volume
          secret:
            secretName: opensearch-curlrc
        - name: opensearch-keystore-default-secret-volume
          secret:
            secretName: opensearch-keystore
{{- end }}