{{- $htadmin_image := .Values.image.htadmin_container_override | default (printf "%s/htadmin:%s" .Values.image.repository .Chart.AppVersion) }}
---
apiVersion: v1
kind: Service
metadata:
  name: htadmin
spec:
  ports:
    - port: 80
      protocol: TCP
      name: http
  selector:
    name: htadmin-deployment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: htadmin-deployment
spec:
  selector:
    matchLabels:
      name: htadmin-deployment
  replicas: 1
  template:
    metadata:
      labels:
        name: htadmin-deployment
    spec:
      containers:
      - name: htadmin-container
        image: "{{ $htadmin_image }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        stdin: false
        tty: true
        securityContext:
          # TODO we should not be using root here
          runAsGroup: 0
          runAsUser: 0
        ports:
          - name: http
            protocol: TCP
            containerPort: 80
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          - configMapRef:
              name: auth-common-env
        env:
          - name: MALCOLM_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.auth.existingSecret | default "auth-env" }}
                key: "{{ if .Values.auth.existingSecret }}{{ .Values.auth.usernameKey }}{{ else }}MALCOLM_USERNAME{{ end }}"
        volumeMounts:
          - mountPath: /var/local/ca-trust/configmap
            name: var-local-catrust-volume
          - mountPath: /var/www/htadmin/auth
            name: htadmin-config-volume
            subPath: "auth"
          - mountPath: /var/www/htadmin/config
            name: htadmin-config-volume
            subPath: "htadmin"
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/container_health.sh
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 15
          successThreshold: 1
          failureThreshold: 10
      initContainers:
      {{ include "malcolm.dirinit.initContainer" (dict
           "root" $
           "name" "htadmin-dirinit-container"
           "env" (list
             (dict "name" "PUSER_MKDIR" "value" "/data/config:auth,htadmin")
           )
           "volumeMounts" (list
             (dict "name" "htadmin-config-volume" "mountPath" "/data/config")
           )
         ) | nindent 6 }}
      volumes:
        - name: var-local-catrust-volume
          configMap:
            name: {{ .Values.ca_trust_configmap_name | default "var-local-catrust" }}
        - name: htadmin-config-volume
          persistentVolumeClaim:
            claimName: config-claim