{{- $strelka_frontend_image := .Values.image.strelka_frontend_container_override | default (printf "%s/strelka-frontend:%s" .Values.image.repository .Chart.AppVersion) }}
{{- $dirinit_image := .Values.image.dirinit_container_override | default (printf "%s/dirinit:%s" .Values.image.repository .Chart.AppVersion) }}
---
apiVersion: v1
kind: Service
metadata:
  name: strelka-frontend
spec:
  ports:
    - port: 57314
      protocol: TCP
      name: enqueue
  selector:
    name: strelka-frontend-deployment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strelka-frontend-deployment
spec:
  selector:
    matchLabels:
      name: strelka-frontend-deployment
  replicas: 1
  template:
    metadata:
      labels:
        name: strelka-frontend-deployment
    spec:
      containers:
      - name: strelka-frontend-container
        image: "{{ $strelka_frontend_image }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        stdin: false
        tty: true
        securityContext:
          # TODO we should not be using root here
          runAsGroup: 0
          runAsUser: 0
        ports:
          - name: health
            containerPort: 8001
            protocol: TCP
          - name: files
            protocol: TCP
            containerPort: 8006
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          - secretRef:
              name: redis-env
          - configMapRef:
              name: pipeline-env
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/container_health.sh
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 15
          successThreshold: 1
          failureThreshold: 10
        volumeMounts:
          - mountPath: /var/local/ca-trust/configmap
            name: var-local-catrust-volume
          - mountPath: "/etc/strelka/configmap"
            name: strelka-frontend-config-volume
          - name: strelka-frontend-logs-volume
            mountPath: /var/log/strelka
            subPath: "strelka-frontend"
      initContainers:
      - name: strelka-frontend-live-dirinit-container
        image: "{{ $dirinit_image }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        stdin: false
        tty: true
        securityContext:
          runAsGroup: 0
          runAsUser: 0
        envFrom:
          - configMapRef:
              name: process-env
        env:
          - name: PUSER_MKDIR
            value: "/data/runtime-logs:strelka-frontend"
        volumeMounts:
          - name: strelka-frontend-logs-volume
            mountPath: "/data/runtime-logs"
      volumes:
        - name: var-local-catrust-volume
          configMap:
            name: {{ .Values.ca_trust_configmap_name | default "var-local-catrust" }}
        - name: strelka-frontend-config-volume
          configMap:
            name: strelka-frontend-config
        - name: strelka-frontend-logs-volume
          persistentVolumeClaim:
            claimName: runtime-logs-claim



