{{- $redisPassword := randAlphaNum 25 }}
{{- $netboxSuperUserPassword := randAlphaNum 25 }}
{{- $netboxSecretKey := randAlphaNum 50 }}
{{- $netboxSuperAPIToken := randAlphaNum 32 }}
{{- $fileExtractServerKey := randAlphaNum 14 }}

{{- if not .Values.auth.existingSecret }}
---
apiVersion: v1
data:
  MALCOLM_USERNAME: {{ .Values.auth.username | b64enc }}
  # the two b64enc's are not a typo: pod expects MALCOLM_PASSWORD to be b64enc'd
  MALCOLM_PASSWORD: {{ .Values.auth.openssl_password | b64enc | b64enc }}
kind: Secret
metadata:
  name: auth-env
type: Opaque

---
apiVersion: v1
data:
  htpasswd: {{ .Values.auth.htpass_cred | b64enc }}
kind: Secret
metadata:
  name: etc-nginx-auth
type: Opaque
{{- end }}

---
apiVersion: v1
data:
  nginx_ldap.conf: {{ .Files.Get "files/nginx_ldap.conf" | b64enc }}
kind: Secret
metadata:
  name: etc-nginx
type: Opaque

---
apiVersion: v1
stringData:
  REDIS_PASSWORD: {{ $redisPassword }}
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_CACHE_HOST: "redis-cache"
  REDIS_CACHE_PORT: "6379"
  REDIS_NETBOX_DATABASE: "0"
  REDIS_ZEEK_FILES_DATABASE: "1"
  REDIS_NETBOX_CACHE_DATABASE: "0"
  REDIS_STRELKA_COORDINATOR_CACHE_DATABASE: "1"
  REDIS_STRELKA_GATEKEEPER_CACHE_DATABASE: "2"
  REDIS_FILESCAN_CACHE_DATABASE: "3"
kind: Secret
metadata:
  name: redis-env
type: Opaque

---
apiVersion: v1
stringData:
  DB_HOST: "{{ .Values.postgres.host }}"
  POSTGRES_HOST: "{{ .Values.postgres.host }}"
  PGPORT: "5432"
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "{{ .Values.postgres.password }}"
  POSTGRES_NETBOX_DB: "{{ .Values.postgres.netbox_db_name }}"
  POSTGRES_NETBOX_USER: "netbox"
  POSTGRES_NETBOX_PASSWORD: "{{ .Values.postgres.password }}"
  POSTGRES_KEYCLOAK_DB: "{{ .Values.postgres.keycloak_db_name }}"
  POSTGRES_KEYCLOAK_USER: "keycloak"
  POSTGRES_KEYCLOAK_PASSWORD: "{{ .Values.postgres.password }}"
  POSTGRES_DISABLED: "{{ not .Values.postgres.enabled }}"  
kind: Secret
metadata:
  name: postgres-env
type: Opaque

---
apiVersion: v1
data:
  DB_USER: {{ "netbox" | b64enc }}
  EMAIL_PASSWORD: ""
  EMAIL_USERNAME: {{ "netbox" | b64enc }}
  NAPALM_PASSWORD: ""
  NAPALM_USERNAME: ""
  REDIS_CACHE_PASSWORD: {{ $redisPassword | b64enc }}
  REDIS_PASSWORD: {{ $redisPassword | b64enc }}
  SECRET_KEY: {{ $netboxSecretKey | b64enc }}
  SUPERUSER_API_TOKEN: {{ $netboxSuperAPIToken | b64enc }}
  SUPERUSER_NAME: {{ "admin" | b64enc }}
  SUPERUSER_PASSWORD: {{ $netboxSuperUserPassword | b64enc }}
  {{- if eq .Values.netbox.mode "remote" }}
  NETBOX_TOKEN: "{{ .Values.netbox.netbox_remote_token | b64enc }}"
  {{- else }}
  NETBOX_TOKEN: ""
  {{- end }}
kind: Secret
metadata:
  name: netbox-secret-env
type: Opaque

---
apiVersion: v1
data:
  .opensearch.primary.curlrc: {{ include "malcolm.curlrc" . }}
  .opensearch.secondary.curlrc: ""
kind: Secret
metadata:
  name: opensearch-curlrc
type: Opaque

---
apiVersion: v1
data:
  # Specifies the password for encrypted Zeek-extracted files served over HTTP
  #   If FILESCAN_HTTP_SERVER_ZIP is true this is the password for the Zip file,
  #   otherwise it is the AES-256-CBC decryption password
  FILESCAN_HTTP_SERVER_KEY: {{ $fileExtractServerKey| b64enc }}
kind: Secret
metadata:
  name: filescan-secret-env
type: Opaque

{{- if or (eq .Values.auth.mode "keycloak") (eq .Values.auth.mode "keycloak_remote") }}
---
apiVersion: v1
stringData:
  KEYCLOAK_AUTH_REALM: "{{ .Values.keycloak.keycloak_auth_realm }}"
  KEYCLOAK_AUTH_REDIRECT_URI: "{{ .Values.keycloak.keycloak_auth_redirect_uri }}"
  KEYCLOAK_AUTH_URL: "{{ .Values.keycloak.keycloak_auth_url }}"
  KEYCLOAK_CLIENT_ID: "{{ .Values.keycloak.keycloak_client_id }}"
  KEYCLOAK_CLIENT_SECRET: "{{ .Values.keycloak.keycloak_client_secret }}"
  KC_CACHE: "{{ .Values.keycloak.kc_cache }}"
  KC_HEALTH_ENABLED: "{{ .Values.keycloak.kc_health_enabled }}"
  KC_HOSTNAME: "{{ .Values.keycloak.kc_hostname }}"
  KC_HOSTNAME_STRICT: "{{ .Values.keycloak.kc_hostname_strict }}"
  KC_HTTP_ENABLED: "{{ .Values.keycloak.kc_http_enabled }}"
  KC_HTTP_RELATIVE_PATH: "{{ .Values.keycloak.kc_http_relative_path }}"
  KC_METRICS_ENABLED: "{{ .Values.keycloak.kc_metrics_enabled }}"
  KC_PROXY_HEADERS: "{{ .Values.keycloak.kc_proxy_headers }}"
  KC_BOOTSTRAP_ADMIN_USERNAME: "{{ .Values.keycloak.kc_bootstrap_admin_username }}"
  KC_BOOTSTRAP_ADMIN_PASSWORD: "{{ .Values.keycloak.kc_bootstrap_admin_password }}"
kind: Secret
metadata:
  name: keycloak-env
{{- end }}
---
{{- if .Values.postgres.is_custom }}
{{- include "netbox.databaseExtravars" . }}
{{- end }}
